#Jekyll configuration
name: Vault Hunters 3rd Edition - SyntheeR's guides
url: "https://vault-hunters.sth.ovh/"
markdown: kramdown
remote_theme: just-the-docs/just-the-docs@v0.4.0.rc3
#remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
